name: PikachuPlugin
version: 1.7
description: Pikachu use thunderbolt.
author: JamieSinn
website: http://dev.bukkit.org/server-mods/pikachuplugin/ 
main: me.JamieSinn.Bukkit.Pikachu
database: false


commands:
  pikachu:
    description: Shocks the location/player targeted



permissions:
  PikachuPlugin.*:
    description: Gives access to all commands
    children:
      PikachuPlugin.aim: true
      PikachuPlugin.player: true
  PikachuPlugin.aim:
    description: Allows you to use /pikachu.
    default: false
  PikachuPlugin.player:
    description: Allows you to use /pikachu <player>.
    default: false
 

