name: Pikachu Plugin
description: Pikachu use Thunderbolt!
version: 1.7
main: me.JamieSinn.Bukkit.PikachuPlugin
author: JamieSinn
website: http://dev.bukkit.org/server-mods/pikachuplugin/

commands:
   pikachu:
      description: Shocks location that you are looking at
      usage: /<command>
      permission: PikachuPlugin.aim
      permission-message: You don't have permission to do this.
   pikachu:
      description: Shocks target Player
      usage: /<command> <player>
      permission: PikachuPlugin.player
      permission-message: You don't have permission to do this.
            
permissions:
    PikachuPlugin.*:
        description: Gives access to all PikachuPlugin commands
        children:
            PikachuPlugin.user: true
            PikachuPlugin.player: true
    PikachuPlugin.aim:
        description: Allows you to use the "/pikachu" command.
        default: op
    PikachuPlugin.player:
        description: Allows you to use the "/pikachu <user>" command.
        default: op 

